[package]
name = "emu8080"
version = "0.1.0"
authors = ["Itamar <itamarx22@gmail.com>"]
edition = "2018"

[workspaces]
members = [
	"intel8080"
]

[dependencies]
intel8080 = { path = "./intel8080" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
